#数据库的连接信息
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.79.201.49:3306/springboot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
#dubbo相关配置(配置ZK的地址)
dubbo:
  application:
    name: dubbo-provider  #给应用取名字, 不要重复就好了 一般写项目名
#  protocol:
#    name: dubbo
#    port: 20880
  registry:
    address: zookeeper://120.79.201.49:2181
  scan:
    base-packages: com.itheima.service #包扫描 业务层的实现类要写在com.itheima.service
