server:
  port: 18084
spring:
  application:
    name: mall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos地址
    gateway:
     default-filters:
        - AddResponseHeader=name,xiaoyezi
     routes: #路由配置
        - id: mall-order #唯一标识,默认是UUID
          uri: lb://mall-order #动态路由
          predicates: #条件, 用于请求网络路径的匹配规则
            - Path=/order/** #eg localhost:18084/order/1-->localhost:18082/order/1
        - id: mall-goods #唯一标识,默认是UUID
          uri: lb://mall-goods #动态路由
          predicates: #条件, 用于请求网络路径的匹配规则
            - Path=/goods/**
          filters:
            - AddRequestParameter=name,zs
            - StripPrefix=1  #去掉路径前缀 去掉1层  #  localhost:18084/goods/sku/1-->localhost:18081/sku/1
     globalcors:
        cors-configurations:
          '[/**]': # 匹配所有的请求
            allowedOrigins: "*" # 允许所有的域来访问
            allowedHeaders: "*" # 允许所有的头携带过来
            allowedMethods:  # 允许以下的方法的请求来访问
              - GET
              - DELETE
              - POST
              - PUT

